name       : ninvaders
version    : 0.1.1
release    : 3
source     :
    - http://ufpr.dl.sourceforge.net/project/ninvaders/ninvaders/0.1.1/ninvaders-0.1.1.tar.gz : bfbc5c378704d9cf5e7fed288dac88859149bee5ed0850175759d310b61fd30b
homepage   : http://ninvaders.sourceforge.net/
license    : GPL-2.0-or-later
component  : games.arcade
summary    : A space invaders-like game using ncurses
description: |
    A space invaders-like game using ncurses. Right now you are earth's only hope to save it from alien invaders from space. Make your job, and make it good, mankind believes in you...
environment: |
    export CFLAGS="${CFLAGS} -fcommon"
    export LDFLAGS="${LDFLAGS} -Wl,--allow-multiple-definition"
build      : |
    %make
install    : |
    install -Dm00755 nInvaders $installdir/usr/bin/nInvaders
