name        : ninvaders
version     : 0.1.1
release     : 1
source      :
    - http://ufpr.dl.sourceforge.net/project/ninvaders/ninvaders/0.1.1/ninvaders-0.1.1.tar.gz : bfbc5c378704d9cf5e7fed288dac88859149bee5ed0850175759d310b61fd30b
license     : GPL-2.0
summary     : A space invaders-like game using ncurses
builddeps   :
    - ncurses-devel
description : |
    A space invaders-like game using ncurses. Right now you are earth's only hope to save     it from alien invaders from space. Make your job, and make it good, mankind believes in you...
build      : |
    %make
install    : |
    install -D nInvaders %installroot%/usr/bin/nInvaders
    install -d %installroot%/usr/share/doc/nInvaders
    install README gpl.txt ChangeLog %installroot%/usr/share/doc/nInvaders/
